version: '3.9'

services:
  postgres:
    container_name: database_metropolitan
    image: metropolitan_postgres:v1
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=metropolitan_db